#!/usr/bin/env python3
"""
Simplified country media publisher.

Workflow:
  1. python publish.py Armenia --fetch-wiki    # save Wikipedia text to paste into Claude.ai
  2. Generate content with Claude.ai, save files to outputs/
  3. python publish.py Armenia --voice-only    # generate audio from script
  4. python publish.py Armenia                 # publish everything to Telegram

Expected files in outputs/:
  {country}_telegram.txt   — country info block (caption)
  {country}_links.txt      — YouTube links section
  {country}_fun_fact.txt   — fun facts (optional)
  {country}_script.txt     — Persian script for TTS (used by --voice-only)
  {country}.mp3            — audio (generated by --voice-only, published on next run)
  {country}_image.png/jpg  — image (auto-fetched from Wikimedia if missing)
"""

import argparse
import os
from pathlib import Path

from modules.telegram_post_generator_manual import is_caption_within_limit, telegram_caption_length
from modules.telegram_publisher import send_audio, send_message, send_photo
from modules.wikimedia_fetcher import search_country_image

TELEGRAM_CAPTION_LIMIT = 1024


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8").strip() if path.exists() else ""


def _find_image(out_dir: Path, country: str) -> str | None:
    for ext in (".png", ".jpg", ".jpeg"):
        p = out_dir / f"{country}_image{ext}"
        if p.exists():
            return str(p)
    return None


def cmd_fetch_wiki(country: str) -> None:
    from modules.wiki_fetcher import fetch_wikipedia_full_text
    out_dir = Path("outputs")
    out_dir.mkdir(exist_ok=True)
    print(f"Fetching Wikipedia text for {country}...")
    text = fetch_wikipedia_full_text(country)
    out_path = out_dir / f"{country}_wiki.txt"
    out_path.write_text(text, encoding="utf-8")
    print(f"Saved: {out_path}  ({len(text):,} chars)")
    print("Paste this into Claude.ai to generate your content files.")


def cmd_voice(country: str) -> None:
    script_path = Path("outputs") / f"{country}_script.txt"
    if not script_path.exists():
        print(f"Script not found: {script_path}")
        return
    script_text = script_path.read_text(encoding="utf-8").strip()
    if not script_text:
        print("Script file is empty.")
        return

    from modules.elevenlabs_tts import (
        build_tts_plan,
        elevenlabs_preflight,
        elevenlabs_script_to_mp3,
        resolve_model_id,
        resolve_voice_id,
    )

    model_id = resolve_model_id()
    voice_id = resolve_voice_id()

    plan = build_tts_plan(script_text, model_id=model_id)
    print(f"TTS plan: model={model_id}, chars={plan['char_count']}, chunks={plan['chunk_count']}")

    preflight = elevenlabs_preflight(voice_id=voice_id, model_id=model_id)
    if preflight.get("voice_name"):
        print(f"Voice: {preflight['voice_name']} ({voice_id})")
    for w in preflight.get("warnings", []):
        print("Warning:", w)

    audio_path = elevenlabs_script_to_mp3(
        script_fa=script_text,
        out_dir="outputs",
        out_mp3_name=f"{country}.mp3",
        voice_id=voice_id,
        model_id=model_id,
    )
    print(f"Audio saved: {audio_path}")


def cmd_publish(country: str, week: str, no_audio: bool) -> None:
    out_dir = Path("outputs")
    caption_text = _read(out_dir / f"{country}_telegram.txt")
    links_text = _read(out_dir / f"{country}_links.txt")
    fun_fact_text = _read(out_dir / f"{country}_fun_fact.txt")
    audio_path = out_dir / f"{country}.mp3"

    if not caption_text:
        print(f"Missing required file: outputs/{country}_telegram.txt")
        return

    # Combine country info + YouTube links into one caption when it fits, otherwise
    # post the country block as the photo caption and send links separately.
    combined = f"{caption_text}\n\n{links_text}" if links_text else caption_text
    split_links = bool(links_text and not is_caption_within_limit(combined))
    photo_caption = caption_text if split_links else combined

    if split_links:
        print(
            f"Combined text is {telegram_caption_length(combined)} chars after entity parsing, above Telegram's {TELEGRAM_CAPTION_LIMIT} "
            "caption limit. Sending links as a separate message."
        )

    # Find or fetch image
    image_path = _find_image(out_dir, country)
    if not image_path:
        print("No image in outputs/. Fetching from Wikimedia...")
        image_path = search_country_image(country)
        if image_path:
            print(f"Image saved: {image_path}")

    # Publish main message
    if image_path:
        ok = send_photo(image_path, photo_caption)
        if ok and split_links:
            ok = send_message(links_text)
    else:
        print("No image available. Sending as text.")
        ok = send_message(combined)
    print("Published." if ok else "Publish failed.")

    # Fun facts
    if ok and fun_fact_text:
        print("Sending fun facts...")
        ok_ff = send_message(fun_fact_text)
        print("Fun facts sent." if ok_ff else "Fun facts failed.")

    # Audio
    if no_audio:
        print("Audio skipped (--no-audio).")
        return

    if not ok:
        print("Skipping audio — main message failed.")
        return

    if audio_path.exists() and audio_path.stat().st_size > 0:
        print("Sending audio...")
        week_tag = f"#week{week.zfill(2)}"
        first_letter = f"#{country[0].upper()}" if country and country[0].isalpha() else ""
        audio_caption = (
            f"مرور صوتی ویکی‌پدیا {country}؛ تهیه شده با هوش مصنوعی\n"
            f"{week_tag} #{country} {first_letter} @countries_AtoZ".strip()
        )
        ok_audio = send_audio(str(audio_path), audio_caption, title=country)
        print("Audio sent." if ok_audio else "Audio failed.")
    else:
        print("No audio file found. Run --voice-only first, or use --no-audio to skip.")


def main():
    parser = argparse.ArgumentParser(
        description="Country media publisher",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("country", help="Country name, e.g. Armenia")
    parser.add_argument(
        "--fetch-wiki",
        action="store_true",
        help="Fetch and save Wikipedia text for Claude.ai",
    )
    parser.add_argument(
        "--voice-only",
        action="store_true",
        help="Generate audio from outputs/<country>_script.txt",
    )
    parser.add_argument(
        "--no-audio",
        action="store_true",
        help="Publish without sending audio",
    )
    parser.add_argument(
        "--week",
        default=os.getenv("WEEK_NUMBER", "02"),
        metavar="N",
        help="Week number for hashtags, e.g. --week 3 (default: env WEEK_NUMBER or 02)",
    )
    args = parser.parse_args()

    if args.fetch_wiki:
        cmd_fetch_wiki(args.country)
    elif args.voice_only:
        cmd_voice(args.country)
    else:
        cmd_publish(args.country, week=args.week, no_audio=args.no_audio)


if __name__ == "__main__":
    main()
